#CLOCK
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33 } [get_ports {clk}]; #IO_L12P_T1_MRCC_14 Sch=gclk
create_clock -add -name sys_clk_pin -period 83.33 -waveform {0 41.66} [get_ports {clk}];

#SEVENSEG - FROM TOP TOO BOTTOM PIO1-8
set_property PACKAGE_PIN M3 [get_ports LED_out[7]]
set_property PACKAGE_PIN L3 [get_ports LED_out[6]]
set_property PACKAGE_PIN A16 [get_ports LED_out[5]]
set_property PACKAGE_PIN K3 [get_ports LED_out[4]]
set_property PACKAGE_PIN C15 [get_ports LED_out[3]]
set_property PACKAGE_PIN H1 [get_ports LED_out[2]] 
set_property PACKAGE_PIN A15 [get_ports LED_out[1]]
set_property PACKAGE_PIN B15 [get_ports LED_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED_out]

#LCD - FROM TOP TOO BOTTOM PIO37-48
set_property PACKAGE_PIN V4 [get_ports LCD_RST]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RST]
set_property PACKAGE_PIN U4 [get_ports LCD_E]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_E]
set_property PACKAGE_PIN V5 [get_ports LCD_RW]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RW]
set_property PACKAGE_PIN W4 [get_ports LCD_BUS[7]]
set_property PACKAGE_PIN U5 [get_ports LCD_BUS[6]]
set_property PACKAGE_PIN U2 [get_ports LCD_BUS[5]]
set_property PACKAGE_PIN W6 [get_ports LCD_BUS[4]]
set_property PACKAGE_PIN U3 [get_ports LCD_BUS[3]]
set_property PACKAGE_PIN U7 [get_ports LCD_BUS[2]]
set_property PACKAGE_PIN W7 [get_ports LCD_BUS[1]]
set_property PACKAGE_PIN U8 [get_ports LCD_BUS[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BUS]
set_property PACKAGE_PIN V8 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]




#################################LOOKUP TABLE#####################################

##CLOCK
#set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK100MHZ }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { CLK100MHZ }];

##ONBOARD LED's
#set_property PACKAGE_PIN C17 [get_ports ledR]
#set_property IOSTANDARD LVCMOS33 [get_ports ledR]
#set_property PACKAGE_PIN B16 [get_ports ledG]
#set_property IOSTANDARD LVCMOS33 [get_ports ledG]
#set_property PACKAGE_PIN B17 [get_ports ledB]
#set_property IOSTANDARD LVCMOS33 [get_ports ledB]


##ONBOARD SWITCHE'S
#set_property PACKAGE_PIN A18 [get_ports SWITCH1]
#set_property IOSTANDARD LVCMOS33 [get_ports SWITCH1]
#set_property PACKAGE_PIN B18 [get_ports SWITCH2]
#set_property IOSTANDARD LVCMOS33 [get_ports SWITCH2]


##ANALOGE PINS
#set_property PACKAGE_PIN G3 [get_ports PIO15P]
#set_property PACKAGE_PIN G2 [get_ports PIO15N]
#set_property PACKAGE_PIN H2 [get_ports PIO16P]
#set_property PACKAGE_PIN J2 [get_ports PIO16N]

##DIGITALE PINS
#set_property PACKAGE_PIN M3 [get_ports PIO1]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO1]
#set_property PACKAGE_PIN L3 [get_ports PIO2]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO2]
#set_property PACKAGE_PIN A16 [get_ports PIO3]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO3]
#set_property PACKAGE_PIN K3 [get_ports PIO4]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO4]
#set_property PACKAGE_PIN C15 [get_ports PIO5]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO5]
#set_property PACKAGE_PIN H1 [get_ports PIO6] 
#set_property IOSTANDARD LVCMOS33 [get_ports PIO6]
#set_property PACKAGE_PIN A15 [get_ports PIO7]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO7]
#set_property PACKAGE_PIN B15 [get_ports PIO8]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO8]
#set_property PACKAGE_PIN A14 [get_ports PIO9]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO9]
#set_property PACKAGE_PIN J3 [get_ports PIO10]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO10]
#set_property PACKAGE_PIN J1 [get_ports PIO11]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO11]
#set_property PACKAGE_PIN K2 [get_ports PIO12]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO12]
#set_property PACKAGE_PIN L1 [get_ports PIO13]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO13]
#set_property PACKAGE_PIN L2 [get_ports PIO14]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO14]
#set_property PACKAGE_PIN M1 [get_ports PIO17]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO17]
#set_property PACKAGE_PIN N3 [get_ports PIO18]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO18]
#set_property PACKAGE_PIN P3 [get_ports PIO19]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO19]
#set_property PACKAGE_PIN M2 [get_ports PIO20]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO20]
#set_property PACKAGE_PIN N1 [get_ports PIO21]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO21]
#set_property PACKAGE_PIN N2 [get_ports PIO22]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO22]
#set_property PACKAGE_PIN P1 [get_ports PIO23] 
#set_property IOSTANDARD LVCMOS33 [get_ports PIO23]
#set_property PACKAGE_PIN R3 [get_ports PIO26]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO26]
#set_property PACKAGE_PIN T3 [get_ports PIO27]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO27]
#set_property PACKAGE_PIN R2 [get_ports PIO28]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO28]
#set_property PACKAGE_PIN T1 [get_ports PIO29]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO29]
#set_property PACKAGE_PIN T2 [get_ports PIO30]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO30]
#set_property PACKAGE_PIN U1 [get_ports PIO31]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO31]
#set_property PACKAGE_PIN W2 [get_ports PIO32]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO32]
#set_property PACKAGE_PIN V2 [get_ports PIO33]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO33]
#set_property PACKAGE_PIN W3 [get_ports PIO34]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO34]
#set_property PACKAGE_PIN V3 [get_ports PIO35]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO35]
#set_property PACKAGE_PIN W5 [get_ports PIO36]
#set_property IOSTANDARD LVCMOS33 [get_ports PI36]
#set_property PACKAGE_PIN V4 [get_ports PIO37]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO37]
#set_property PACKAGE_PIN U4 [get_ports PIO38]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO38]
#set_property PACKAGE_PIN V5 [get_ports PIO39]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO39]
#set_property PACKAGE_PIN W4 [get_ports PIO40]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO40]
#set_property PACKAGE_PIN U5 [get_ports PIO41]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO41]
#set_property PACKAGE_PIN U2 [get_ports PIO42]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO42]
#set_property PACKAGE_PIN W6 [get_ports PIO43]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO43]
#set_property PACKAGE_PIN U3 [get_ports PIO44]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO44]
#set_property PACKAGE_PIN U7 [get_ports PIO45]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO45]
#set_property PACKAGE_PIN W7 [get_ports PIO46]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO46]
#set_property PACKAGE_PIN U8 [get_ports PIO47]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO47]
#set_property PACKAGE_PIN V8 [get_ports PIO48]
#set_property IOSTANDARD LVCMOS33 [get_ports PIO48]